//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLDG_PERMIT
    {
        public string PERMIT_CODE { get; set; }
    }
}
