//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNS_TABLE
    {
        public string FEES_CODE { get; set; }
        public string BNS_CODE { get; set; }
        public string BNS_DESC { get; set; }
        public string MEANS { get; set; }
    }
}
