//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS_CONFIG
    {
        public string BUSS_CONFIGNO { get; set; }
        public string CONFIG_DESC { get; set; }
        public string CONFIG_VALUE { get; set; }
    }
}
