//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEATH_INFO_TMP
    {
        public string OR_NO { get; set; }
        public string D_NAME { get; set; }
        public string D_NATIONALITY { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public string SEX { get; set; }
        public string CEMETERY { get; set; }
        public string DISINTERMENT { get; set; }
        public string INFECTIOUS { get; set; }
        public string EMBALMED { get; set; }
        public string DISPOSITION { get; set; }
        public string TELLER_CODE { get; set; }
        public Nullable<System.DateTime> DEATH_DATE { get; set; }
    }
}
