//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEBIT_CREDIT_X
    {
        public string PAYER_CODE { get; set; }
        public string OR_NO { get; set; }
        public Nullable<System.DateTime> OR_DATE { get; set; }
        public string FORM_TYPE { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string MEMO { get; set; }
        public string CHK_NO { get; set; }
        public System.DateTime DATE_POSTED { get; set; }
        public string TIME_POSTED { get; set; }
        public string USER_CODE { get; set; }
    }
}
