//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_TBL
    {
        public string FORM_FLD { get; set; }
        public string FORM_DESC { get; set; }
    }
}
