//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARCSEntities : DbContext
    {
        public ARCSEntities()
            : base("name=ARCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BUSINESS_CONFIG> BUSINESS_CONFIG { get; set; }
        public DbSet<QUARTERLYFEE_TBL> QUARTERLYFEE_TBL { get; set; }
        public DbSet<RECEIPTS_PAYMENT> RECEIPTS_PAYMENT { get; set; }
        public DbSet<RECEIPTS_TBL> RECEIPTS_TBL { get; set; }
        public DbSet<DEATH_INFO> DEATH_INFO { get; set; }
        public DbSet<DEATH_INFO_TMP> DEATH_INFO_TMP { get; set; }
        public DbSet<DEBIT_CREDIT> DEBIT_CREDIT { get; set; }
        public DbSet<DEBIT_CREDIT_X> DEBIT_CREDIT_X { get; set; }
        public DbSet<DISTRICT> DISTRICTS { get; set; }
        public DbSet<FORM_TBL> FORM_TBL { get; set; }
        public DbSet<PARTIAL_REMIT> PARTIAL_REMIT { get; set; }
        public DbSet<SYSLINK_DIC_TBL> SYSLINK_DIC_TBL { get; set; }
    }
}
