//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIAL_REMIT
    {
        public string TELLER_CODE { get; set; }
        public string RCD_SERIES { get; set; }
        public Nullable<decimal> P1000 { get; set; }
        public Nullable<decimal> P500 { get; set; }
        public Nullable<decimal> P200 { get; set; }
        public Nullable<decimal> P100 { get; set; }
        public Nullable<decimal> P50 { get; set; }
        public Nullable<decimal> P20 { get; set; }
        public Nullable<decimal> P10 { get; set; }
        public Nullable<decimal> C10 { get; set; }
        public Nullable<decimal> C5 { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C005 { get; set; }
        public Nullable<decimal> C0025 { get; set; }
        public Nullable<decimal> C001 { get; set; }
        public Nullable<decimal> C0005 { get; set; }
        public Nullable<decimal> C0001 { get; set; }
        public Nullable<decimal> TOTAL_CASH { get; set; }
        public Nullable<decimal> TOTAL_CHECK { get; set; }
        public Nullable<decimal> TOTAL_COLLECTION { get; set; }
        public string OR_FROM { get; set; }
        public string OR_TO { get; set; }
        public Nullable<System.DateTime> OR_DATE { get; set; }
        public Nullable<System.DateTime> DT_SAVE { get; set; }
    }
}
