//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPTS_TBL
    {
        public string OR_NO { get; set; }
        public System.DateTime OR_DATE { get; set; }
        public string TAX_YEAR { get; set; }
        public string REF_NO { get; set; }
        public string TAXPAYER_NM { get; set; }
        public string MEMO_TAG { get; set; }
        public string ENCODEDBY { get; set; }
        public System.DateTime DATE_ENCODED { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
    }
}
