//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPTS_PAYMENT
    {
        public string OR_NO { get; set; }
        public string QTR_PAID { get; set; }
        public string FEES_CODE { get; set; }
        public decimal FEES_AMOUNT { get; set; }
    }
}
