//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSLINK_DIC_TBL
    {
        public string SYSNAME { get; set; }
        public string GEN_CODE { get; set; }
        public string FEES_CODE { get; set; }
        public string NGAS_ACCT_CODE { get; set; }
    }
}
