//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPTEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWN_NAMES
    {
        public string OWN_CODE { get; set; }
        public string OWN_LN { get; set; }
        public string OWN_FN { get; set; }
        public string OWN_MI { get; set; }
        public string OWN_ADDR { get; set; }
        public string OWN_BRGY { get; set; }
        public string OWN_MUN { get; set; }
        public string OWN_PROV { get; set; }
        public string OWN_TELNO { get; set; }
        public string OWN_ZIP { get; set; }
        public string OWN_EMAIL { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string OWN_DIST { get; set; }
        public string TYPE_FLD { get; set; }
    }
}
